# Generated by Django 4.2 on 2023-06-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stcokinhand_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_code', to='stocks.stcokinhand'),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='buyamount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='buyquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='sellamount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='sellquantity',
            field=models.IntegerField(default=0),
        ),
    ]
