# Generated by Django 4.2 on 2023-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_record_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('value', models.FloatField(default=0)),
                ('buyamount', models.FloatField(default=0)),
                ('sellamount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('pre_total', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='stcokinhand',
            name='profit_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stcokinhand',
            name='profit_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stcokinhand',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='buyamount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='estimation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='preclose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stcokinhand',
            name='sellamount',
            field=models.FloatField(default=0),
        ),
    ]
